[workspace]
members = [
    "program",
    "script",
]
resolver = "2"

[profile.test]
opt-level = 3
debug = true
debug-assertions = true
incremental = false
lto = "thin"

[profile.release]
lto = "fat"
